console.log("My first console project");
var Firstname="ranbir";
var Lastname="kapoor";
var fullname=Firstname.concat(Lastname);
console.log(fullname);
var a=10;
var b=5;
var add= a + b;
console.log(add);
var c=8;
var d=3;
var add2= c - d;
console.log(add2);
var e=25;
var f=2;
var add3= e * f;
console.log(add3);
var g=12;
var h=6;
var add4= g / h;
console.log(add4);